# Generated by Django 3.2.9 on 2022-02-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nome',
            field=models.CharField(help_text='Nome do departamento', max_length=100),
        ),
    ]
